version: '3.4'

services:
  bookapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=Book
    ports:
      - "7100:80"

  userui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=User
      - ServiceUrls__AddReview=http://bookapi/api/books/{0}/reviews
      - ServiceUrls__ListReview=http://bookapi/api/books/{0}/reviews
      - ServiceUrls__History=http://bookapi/api/books/{0}/completed
      - ServiceUrls__ListBooks=http://bookapi/api/books
      - ServiceUrls__GetBookById=http://bookapi/api/books/{0}
    ports:
      - "7110:80"

  adminui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=Admin
      - ServiceUrls__AuthUrl=http://bookapi/connect/token
      - ServiceUrls__ListBooks=http://bookapi/api/books
      - ServiceUrls__GetBookById=http://bookapi/api/books/{0}
      - ServiceUrls__PostBook=http://bookapi/api/books
      - ServiceUrls__UpdateBook=http://bookapi/api/books/{0}
      - ServiceUrls__DeleteBook=http://bookapi/api/books/{0}
    ports:
      - "7120:80"