version: '3.4'

services:
  bookapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=Book
    ports:
      - "7100:80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=User
    ports:
      - "7200:80"

  adminui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnectionDetails__MongoConnection=mongodb://nosql.data
      - DbConnectionDetails__MongoDatabaseName=Admin
      - ServiceUrls__AuthUrl=http://bookapi/connect/token
      - ServiceUrls__ListBooks=http://bookapi/api/books
      - ServiceUrls__GetBookById=http://bookapi/api/books/{0}
      - ServiceUrls__PostBook=http://bookapi/api/books
      - ServiceUrls__UpdateBook=http://bookapi/api/books/{0}
      - ServiceUrls__DeleteBook=http://bookapi/api/books/{0}
    ports:
      - "7300:80"